### ISSUE TITLE
APNS server - prod - does not work

### ISSUE THREAD

**Issue by pkasson** [jchambers/pushy-console#25]
If I choose the development server it works.

I thought Apple changed the APNS to be all inclusive, all environments ?

**Comment by jchambers** [comment]
Can you please be more specific than "does not work?" What are you getting for an error message? What kind of credentials are you using?

**Comment by pkasson** [comment]
Sorry for the traditional IT response of not working.  When I switch to using the prod APNS server from the first drop down (api.push.apple.com), it fails, , the logs at the bottom say under status 'Rejected' and the Details say 'BadDeviceToken'

**Comment by jchambers** [comment]
Right; so _credentials_ (your certificate/token) work across environments, but receiving devices will generate different tokens depending on which environment they're in. Your phone's APNs token for production is different from its token in development.

The problem here is that you're trying to use your phone's development token in a production environment.
